name: Deploy projects to Digital Ocean

on:
  push:
    branches: [main,development]

env:  
  LOCAL_REMI_CLIENT_PATH: remi_client
  LOCAL_REMI_SERVER_PATH: remi_server
  DROPLET_REMI_CLIENT_PATH: /var/www/remi.gobconsult.com/remi_client
  DROPLET_REMI_SERVER_PATH: /var/www/remi.gobconsult.com/remi_server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create PM2 instances if not exist
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: DROPLET_REMI_SERVER_PATH
        DROPLET_REMI_SERVER_PATH: /var/www/remi.gobconsult.com/remi_server
        script: |
          echo "DROPLET_REMI_SERVER_PATH: $DROPLET_REMI_SERVER_PATH"
          SERVER_BIN_PATH=$DROPLET_REMI_SERVER_PATH/bin/www
          echo "SERVER_BIN_PATH: $SERVER_BIN_PATH"
          if ! pm2 describe remi_server >/dev/null 2>&1; then
            pm2 start --name remi_server --interpreter node $SERVER_BIN_PATH
          fi

    #- name: Deploy and restart server
    #  uses: appleboy/ssh-action@master
    #  with:
    #    host: ${{ secrets.SSH_HOST }}
    #    username: ${{ secrets.SSH_USER }}
    #    key: ${{ secrets.SSH_PRIVATE_KEY }}
    #    envs: DROPLET_REMI_SERVER_PATH
    #    DROPLET_REMI_SERVER_PATH: /var/www/remi.gobconsult.com/remi_server
    #    script: |
    #      pm2 stop remi_server || true
    #      rsync -avz --delete --exclude '.env' --exclude 'node_modules' $GITHUB_WORKSPACE/remi_server/ $DROPLET_REMI_SERVER_PATH/
    #      cd $DROPLET_REMI_SERVER_PATH && npm install && pm2 start bin/www --name remi_server

    - name: Deploy and build client project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: DROPLET_REMI_CLIENT_PATH
        DROPLET_REMI_CLIENT_PATH: /var/www/remi.gobconsult.com/remi_client
        script: |
          echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
          echo "DROPLET_REMI_CLIENT_PATH: $DROPLET_REMI_CLIENT_PATH"
          echo "root ech:"
          ls -la
          echo "Listing contents of source directory:"
          ls -la ${{ github.workspace }}/remi_client/
          echo "Listing contents of source directory client:"
          ls -la ${{ github.workspace }}
          rsync -avz --delete --exclude 'node_modules' --exclude '.env' ${{ github.workspace }}/remi_client/ $DROPLET_REMI_CLIENT_PATH/
#          cd $DROPLET_REMI_CLIENT_PATH && npm install && npm run build
