name: Deploy projects to Digital Ocean

on:
  push:
    branches: [main]

env:  
  LOCAL_REMI_CLIENT_PATH: remi_client
  LOCAL_REMI_SERVER_PATH: remi_server
  DROPLET_REMI_CLIENT_PATH: /var/www/remi.gobconsult.com/remi_client
  DROPLET_REMI_SERVER_PATH: /var/www/remi.gobconsult.com/remi_server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        ls
        echo "Current directory: $(pwd)"
        echo "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/$LOCAL_REMI_CLIENT_PATH && npm install
        cd $GITHUB_WORKSPACE/$LOCAL_REMI_SERVER_PATH && npm install

    - name: Build client project
      run: |
        cd $GITHUB_WORKSPACE/$LOCAL_REMI_CLIENT_PATH && npm run build

    - name: Create PM2 instances if not exist
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          if ! pm2 describe remi_client >/dev/null 2>&1; then
            pm2 start $DROPLET_REMI_CLIENT_PATH --name remi_client
          fi
          if ! pm2 describe remi_server >/dev/null 2>&1; then
            cd $DROPLET_REMI_SERVER_PATH && pm2 start bin/www --name remi_server
          fi
    - name: Deploy and restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pm2 stop remi_server || true
          rsync -avz --delete --exclude '.env' --exclude 'node_modules' $GITHUB_WORKSPACE/remi_server/ $DROPLET_REMI_SERVER_PATH/
          cd $DROPLET_REMI_SERVER_PATH && npm install && pm2 start bin/www --name remi_server

#    - name: Deploy client project
#      uses: appleboy/scp-action@master
#      with:
#        host: ${{ secrets.SSH_HOST }}
#        username: ${{ secrets.SSH_USER }}
#        key: ${{ secrets.SSH_PRIVATE_KEY }}
#        source: $GITHUB_WORKSPACE/remi_client/build/
#        target: $DROPLET_REMI_CLIENT_PATH/public/


