name: Deploy projects to Digital Ocean

on:
  push:
    branches: [main,development]
    #branches: [main]

env:  
  LOCAL_REMI_CLIENT_PATH: remi_client
  LOCAL_REMI_SERVER_PATH: remi_server
  DROPLET_REMI_CLIENT_PATH: /var/www/remi.gobconsult.com/remi_client
  DROPLET_REMI_SERVER_PATH: /var/www/remi.gobconsult.com/remi_server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        ls
        echo "Current directory: $(pwd)"
        echo "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/$LOCAL_REMI_CLIENT_PATH && npm install
        cd $GITHUB_WORKSPACE/$LOCAL_REMI_SERVER_PATH && npm install

    - name: Build client project
      run: |
        cd $GITHUB_WORKSPACE/$LOCAL_REMI_CLIENT_PATH && npm run build

    - name: Restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pm2 stop remi_server || true
          rm -rf $DROPLET_REMI_SERVER_PATH/*
          cp -r $GITHUB_WORKSPACE/remi_server/* $DROPLET_REMI_SERVER_PATH/
          cd $DROPLET_REMI_SERVER_PATH && pm2 start app.js

    - name: Deploy client project
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: $GITHUB_WORKSPACE/remi_client/build/
        target: $DROPLET_REMI_CLIENT_PATH/public/
